"""
STT Transcription Tests
=======================

Tests Alibaba Bailian Qwen-ASR (qwen3-asr-flash) directly:

- Transcribes the WAV fixture files generated by the TTS tests
- Measures STT latency per scenario
- Validates round-trip text accuracy (TTS → STT) using fuzzy matching
- Tests with both Chinese and English audio

All latency metrics are logged to tests/e2e/test_run.log in real-time.

Depends on TTS fixture files in tests/e2e/fixtures/audio/.
Run TTS tests first if fixtures are missing, or let the ``audio_fixtures``
conftest fixture generate them automatically.

Run:
    ALI_BAILIAN_API_KEY=sk-... pytest tests/e2e/test_stt_transcription.py -v -s
"""

import os
import time
from difflib import SequenceMatcher
from typing import Tuple

import numpy as np
import pytest
from loguru import logger

from tests.e2e.conftest import (
    SCENARIOS,
    TTS_SAMPLE_RATE,
    read_wav_to_numpy,
    save_pcm_as_wav,
    collect_tts_stream,
)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _similarity(a: str, b: str) -> float:
    """Sequence-match ratio between two strings (0–1)."""
    # Normalise: strip spaces, lower-case for CJK-safe comparison
    a = a.strip().lower().replace(" ", "")
    b = b.strip().lower().replace(" ", "")
    return SequenceMatcher(None, a, b).ratio()


async def _ensure_fixture(key: str, tts_client, audio_fixtures_dir) -> str:
    """Return fixture path, generating the WAV via TTS if it doesn't exist."""
    path = str(audio_fixtures_dir / f"{key}.wav")
    if not os.path.exists(path):
        text, _ = SCENARIOS[key]
        pcm, _, _ = await collect_tts_stream(tts_client, text)
        assert pcm, f"TTS returned no audio when creating fixture for {key}"
        save_pcm_as_wav(pcm, path)
    return path


# ── Latency tests ─────────────────────────────────────────────────────────────

class TestSTTLatency:
    """
    Measure how long the STT API takes per scenario.
    Also verifies that a non-empty string is returned.
    """

    @pytest.mark.asyncio
    async def test_stt_latency_short_zh(
        self, stt_client, tts_client, audio_fixtures_dir, latency_tracker
    ):
        path = await _ensure_fixture("short_zh", tts_client, audio_fixtures_dir)
        audio, sr = read_wav_to_numpy(path)

        t0 = time.perf_counter()
        text, ok = await stt_client.transcribe(audio, sample_rate=sr)
        latency_ms = (time.perf_counter() - t0) * 1000

        assert ok, f"STT returned failure: {text}"
        assert text.strip(), "STT returned empty string"
        latency_tracker.record("stt_latency_ms", latency_ms, scenario="short_zh")
        print(f"\nshort_zh STT: {latency_ms:.0f}ms → \"{text}\"")

    @pytest.mark.asyncio
    async def test_stt_latency_short_en(
        self, stt_client, tts_client, audio_fixtures_dir, latency_tracker
    ):
        path = await _ensure_fixture("short_en", tts_client, audio_fixtures_dir)
        audio, sr = read_wav_to_numpy(path)

        t0 = time.perf_counter()
        text, ok = await stt_client.transcribe(audio, sample_rate=sr)
        latency_ms = (time.perf_counter() - t0) * 1000

        assert ok, f"STT returned failure: {text}"
        assert text.strip(), "STT returned empty string"
        latency_tracker.record("stt_latency_ms", latency_ms, scenario="short_en")
        print(f"\nshort_en STT: {latency_ms:.0f}ms → \"{text}\"")

    @pytest.mark.asyncio
    async def test_stt_latency_medium_zh(
        self, stt_client, tts_client, audio_fixtures_dir, latency_tracker
    ):
        path = await _ensure_fixture("medium_zh", tts_client, audio_fixtures_dir)
        audio, sr = read_wav_to_numpy(path)

        t0 = time.perf_counter()
        text, ok = await stt_client.transcribe(audio, sample_rate=sr)
        latency_ms = (time.perf_counter() - t0) * 1000

        assert ok, f"STT returned failure: {text}"
        assert text.strip(), "STT returned empty string"
        latency_tracker.record("stt_latency_ms", latency_ms, scenario="medium_zh")
        print(f"\nmedium_zh STT: {latency_ms:.0f}ms → \"{text}\"")

    @pytest.mark.asyncio
    async def test_stt_latency_medium_en(
        self, stt_client, tts_client, audio_fixtures_dir, latency_tracker
    ):
        path = await _ensure_fixture("medium_en", tts_client, audio_fixtures_dir)
        audio, sr = read_wav_to_numpy(path)

        t0 = time.perf_counter()
        text, ok = await stt_client.transcribe(audio, sample_rate=sr)
        latency_ms = (time.perf_counter() - t0) * 1000

        assert ok, f"STT returned failure: {text}"
        assert text.strip(), "STT returned empty string"
        latency_tracker.record("stt_latency_ms", latency_ms, scenario="medium_en")
        print(f"\nmedium_en STT: {latency_ms:.0f}ms → \"{text}\"")


# ── Round-trip accuracy tests ─────────────────────────────────────────────────

class TestSTTRoundTripAccuracy:
    """
    TTS → WAV → STT round-trip accuracy.

    The transcribed text should be semantically close to the original.
    We use SequenceMatcher similarity as a proxy metric.  A score of ≥ 0.5
    is a soft pass (TTS+STT combo may add/drop function words).
    """

    @pytest.mark.asyncio
    async def test_roundtrip_short_zh(
        self, stt_client, tts_client, audio_fixtures_dir, latency_tracker
    ):
        original, _ = SCENARIOS["short_zh"]
        path = await _ensure_fixture("short_zh", tts_client, audio_fixtures_dir)
        audio, sr = read_wav_to_numpy(path)

        t0 = time.perf_counter()
        transcribed, ok = await stt_client.transcribe(audio, sample_rate=sr)
        elapsed_ms = (time.perf_counter() - t0) * 1000

        assert ok
        sim = _similarity(original, transcribed)
        latency_tracker.record("stt_roundtrip_similarity", sim * 1000, scenario="short_zh")  # stored ×1000

        print(
            f"\nround-trip short_zh:"
            f"\n  original    : {original}"
            f"\n  transcribed : {transcribed}"
            f"\n  similarity  : {sim:.2%}"
            f"\n  latency     : {elapsed_ms:.0f} ms"
        )
        assert sim >= 0.4, (
            f"Round-trip similarity too low: {sim:.2%}\n"
            f"  original={original!r}\n  got={transcribed!r}"
        )

    @pytest.mark.asyncio
    async def test_roundtrip_short_en(
        self, stt_client, tts_client, audio_fixtures_dir, latency_tracker
    ):
        original, _ = SCENARIOS["short_en"]
        path = await _ensure_fixture("short_en", tts_client, audio_fixtures_dir)
        audio, sr = read_wav_to_numpy(path)

        t0 = time.perf_counter()
        transcribed, ok = await stt_client.transcribe(audio, sample_rate=sr)
        elapsed_ms = (time.perf_counter() - t0) * 1000

        assert ok
        sim = _similarity(original, transcribed)
        latency_tracker.record("stt_roundtrip_similarity", sim * 1000, scenario="short_en")

        print(
            f"\nround-trip short_en:"
            f"\n  original    : {original}"
            f"\n  transcribed : {transcribed}"
            f"\n  similarity  : {sim:.2%}"
            f"\n  latency     : {elapsed_ms:.0f} ms"
        )
        assert sim >= 0.4, (
            f"Round-trip similarity too low: {sim:.2%}\n"
            f"  original={original!r}\n  got={transcribed!r}"
        )

    @pytest.mark.asyncio
    async def test_roundtrip_medium_zh(
        self, stt_client, tts_client, audio_fixtures_dir, latency_tracker
    ):
        original, _ = SCENARIOS["medium_zh"]
        path = await _ensure_fixture("medium_zh", tts_client, audio_fixtures_dir)
        audio, sr = read_wav_to_numpy(path)

        transcribed, ok = await stt_client.transcribe(audio, sample_rate=sr)
        assert ok
        sim = _similarity(original, transcribed)
        latency_tracker.record("stt_roundtrip_similarity", sim * 1000, scenario="medium_zh")

        print(
            f"\nround-trip medium_zh:"
            f"\n  original    : {original}"
            f"\n  transcribed : {transcribed}"
            f"\n  similarity  : {sim:.2%}"
        )
        assert sim >= 0.4, f"similarity={sim:.2%}"


# ── Silence / edge-case handling ──────────────────────────────────────────────

class TestSTTEdgeCases:
    """Verify graceful handling of unusual inputs."""

    @pytest.mark.asyncio
    async def test_very_short_audio(self, stt_client):
        """0.3 s of silence – API should return empty text or error without crashing."""
        silence = np.zeros(int(0.3 * 16000), dtype=np.float32)
        text, _ = await stt_client.transcribe(silence, sample_rate=16000)
        # We don't assert on content, just that it doesn't raise
        assert isinstance(text, str)

    @pytest.mark.asyncio
    async def test_pure_tone_audio(self, stt_client):
        """440 Hz sine wave – shouldn't crash, should return empty or noise text."""
        t = np.linspace(0, 1.0, 16000, endpoint=False)
        tone = (np.sin(2 * np.pi * 440 * t) * 0.5).astype(np.float32)
        text, _ = await stt_client.transcribe(tone, sample_rate=16000)
        assert isinstance(text, str)
        print(f"\npure tone transcription: {text!r}")
